version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  php:
    image: php:8.3-fpm
    volumes:
      - ./web:/var/www/html